spring:
  application:
    name: KeyKloackLab
  data:
    mongodb:
      host: localhost
      port: 27017
      database: open-source-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:9090/realms/Open
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: open-rest-api